name: 3TS CI

on:
  push:
    branches:
      - coo-consistency-check
  pull_request:
    branches:
      - coo-consistency-check

jobs:
  compile_with_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Docker
      run: curl -s https://get.docker.com/ | sh

    - name: Pull Docker image
      run: docker pull registry.cn-hangzhou.aliyuncs.com/open_projects/3ts_coo:1.0

    - name: List Docker images
      run: docker images

    - name: Run Docker container
      run: |
        IMAGE_ID=$(docker images -q registry.cn-hangzhou.aliyuncs.com/open_projects/3ts_coo:1.0)
        docker run -d --name 3ts_container $IMAGE_ID /bin/bash

    - name: Compile inside Docker
      run: |
        docker exec -it 3ts_container cmake -S /3TS/src/dbtest
        docker exec -it 3ts_container make -C /3TS/src/dbtest

  compile_without_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y cmake make g++

    - name: Compile using CMake
      run: |
        cd src/dbtest
        cmake -S ./
        make

