name: 3TS CI

on:
  push:
    branches:
      - coo-consistency-check
  pull_request:
    branches:
      - coo-consistency-check

jobs:
  setup_environment_and_compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        echo "Setting up build environment..."
        sudo apt-get update && sudo apt-get install -y cmake make g++ libgflags-dev unixodbc-dev odbcinst odbcinst1debian2
        echo "Build environment setup complete."

    - name: Install Docker
      run: curl -s https://get.docker.com/ | sh

    - name: Pull Docker image
      run: docker pull registry.cn-hangzhou.aliyuncs.com/open_projects/3ts_coo:1.0

    - name: List Docker images
      run: docker images

    - name: Run Docker container with volume
      run: |
        IMAGE_ID=$(docker images -q registry.cn-hangzhou.aliyuncs.com/open_projects/3ts_coo:1.0)
        docker run -d --name 3ts_container -v ${{ github.workspace }}:/src $IMAGE_ID tail -f /dev/null

    - name: Compile inside Docker
      run: |
        echo "Running CMake in Docker..."
        docker exec -i 3ts_container bash -c "cmake -DCMAKE_PREFIX_PATH=/usr/include -S /src/src/dbtest"
        echo "Running Make in Docker..."
        docker exec -i 3ts_container bash -c "make -C /src/src/dbtest"

    - name: Clean up Docker container
      run: docker rm -f 3ts_container

    - name: Compile without Docker
      run: |
        echo "Compiling using CMake..."
        cd src/dbtest
        cmake -DCMAKE_PREFIX_PATH=/usr/include -S ./
        make
        echo "Compilation finished."
